import { createUseStyles } from "react-jss";

const useStyles = createUseStyles({
  overlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    backdropFilter: "blur(4px)",
    zIndex: 2000,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  modal: {
    backgroundColor: "#12162e",
    borderRadius: "20px",
    width: "420px",
    maxWidth: "90vw",
    border: "1px solid rgba(167, 139, 250, 0.15)",
    boxShadow: "0 24px 64px rgba(0, 0, 0, 0.5)",
    overflow: "hidden",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "24px 28px 0",
  },
  title: {
    fontSize: "1.3rem",
    fontWeight: 700,
    color: "#fff",
    margin: 0,
  },
  closeButton: {
    background: "rgba(255, 255, 255, 0.06)",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    borderRadius: "10px",
    color: "#94a3b8",
    fontSize: "1.1rem",
    width: "36px",
    height: "36px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.2s ease",
    "&:hover": {
      background: "rgba(255, 255, 255, 0.1)",
      color: "#fff",
    },
  },
  tabs: {
    display: "flex",
    gap: "0",
    padding: "20px 28px 0",
  },
  tab: {
    flex: 1,
    background: "transparent",
    border: "none",
    borderBottom: "2px solid rgba(255, 255, 255, 0.08)",
    color: "#64748b",
    padding: "10px 0",
    fontSize: "0.9rem",
    fontWeight: 500,
    cursor: "pointer",
    transition: "all 0.2s ease",
    fontFamily: "inherit",
    "&:hover": {
      color: "#94a3b8",
    },
  },
  tabActive: {
    color: "#a78bfa",
    borderBottom: "2px solid #a78bfa",
    fontWeight: 600,
  },
  body: {
    padding: "24px 28px 28px",
  },
  form: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "16px",
  },
  inputGroup: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "6px",
  },
  label: {
    fontSize: "0.78rem",
    fontWeight: 500,
    color: "rgba(255, 255, 255, 0.5)",
    letterSpacing: "0.5px",
    textTransform: "uppercase" as const,
  },
  input: {
    background: "rgba(255, 255, 255, 0.06)",
    border: "1.5px solid rgba(255, 255, 255, 0.1)",
    borderRadius: "12px",
    padding: "11px 14px",
    fontSize: "0.9rem",
    color: "#fff",
    outline: "none",
    transition: "all 0.25s ease",
    fontFamily: "inherit",
    "&:focus": {
      borderColor: "#a78bfa",
      background: "rgba(167, 139, 250, 0.08)",
    },
    "&::placeholder": {
      color: "rgba(255, 255, 255, 0.2)",
    },
  },
  select: {
    background: "rgba(255, 255, 255, 0.06)",
    border: "1.5px solid rgba(255, 255, 255, 0.1)",
    borderRadius: "12px",
    padding: "11px 14px",
    fontSize: "0.9rem",
    color: "#fff",
    outline: "none",
    transition: "all 0.25s ease",
    fontFamily: "inherit",
    cursor: "pointer",
    "&:focus": {
      borderColor: "#a78bfa",
      background: "rgba(167, 139, 250, 0.08)",
    },
    "& option": {
      background: "#12162e",
      color: "#fff",
    },
  },
  submitButton: {
    background: "linear-gradient(135deg, #7c3aed, #a78bfa)",
    border: "none",
    borderRadius: "12px",
    color: "#fff",
    padding: "12px",
    fontSize: "0.9rem",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.25s ease",
    letterSpacing: "0.3px",
    marginTop: "4px",
    fontFamily: "inherit",
    boxShadow: "0 4px 14px rgba(124, 58, 237, 0.35)",
    "&:hover": {
      background: "linear-gradient(135deg, #6d28d9, #8b5cf6)",
      boxShadow: "0 6px 20px rgba(124, 58, 237, 0.5)",
      transform: "translateY(-1px)",
    },
    "&:disabled": {
      opacity: 0.6,
      cursor: "not-allowed",
      transform: "none",
    },
  },
  error: {
    background: "rgba(239, 68, 68, 0.1)",
    border: "1px solid rgba(239, 68, 68, 0.3)",
    borderRadius: "10px",
    padding: "10px 14px",
    color: "#fca5a5",
    fontSize: "0.82rem",
    textAlign: "center" as const,
  },
  success: {
    background: "rgba(34, 197, 94, 0.1)",
    border: "1px solid rgba(34, 197, 94, 0.3)",
    borderRadius: "10px",
    padding: "10px 14px",
    color: "#86efac",
    fontSize: "0.82rem",
    textAlign: "center" as const,
  },
});

export default useStyles;
