import { createUseStyles } from "react-jss";

const styles = createUseStyles({
    overlay: {
        position: 'fixed',
        inset: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        backdropFilter: 'blur(4px)',
        zIndex: 2000,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },

    modal: {
        backgroundColor: '#12162e',
        borderRadius: '20px',
        width: '720px',
        maxWidth: '90vw',
        height: '80vh',
        display: 'flex',
        flexDirection: 'column',
        border: '1px solid rgba(167, 139, 250, 0.15)',
        boxShadow: '0 24px 64px rgba(0, 0, 0, 0.5)',
        overflow: 'hidden',
    },

    header: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '24px 28px 16px',
        borderBottom: '1px solid rgba(167, 139, 250, 0.1)',
    },
    title: {
        fontSize: '1.3rem',
        fontWeight: 700,
        color: '#fff',
        margin: 0,
    },
    closeButton: {
        background: 'rgba(255, 255, 255, 0.06)',
        border: '1px solid rgba(255, 255, 255, 0.1)',
        borderRadius: '10px',
        color: '#94a3b8',
        fontSize: '1.1rem',
        width: '36px',
        height: '36px',
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        transition: 'all 0.2s ease',
        '&:hover': {
            background: 'rgba(255, 255, 255, 0.1)',
            color: '#fff',
        },
    },

    filters: {
        display: 'flex',
        gap: '8px',
        padding: '16px 28px',
        flexWrap: 'wrap',
    },
    filterChip: {
        background: 'transparent',
        border: '1.5px solid rgba(255, 255, 255, 0.12)',
        borderRadius: '20px',
        color: '#94a3b8',
        padding: '6px 16px',
        fontSize: '0.8rem',
        fontWeight: 500,
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        '&:hover': {
            borderColor: '#a78bfa',
            color: '#c4b5fd',
        },
    },
    filterChipActive: {
        background: 'rgba(167, 139, 250, 0.15)',
        border: '1.5px solid #a78bfa',
        color: '#a78bfa',
        fontWeight: 600,
    },

    grid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(4, 140px)',
        gap: '14px',
        padding: '8px 28px 28px',
        overflowY: 'auto',
        flex: 1,
        justifyContent: 'center',
    },

    card: {
        background: 'linear-gradient(145deg, #1a1e3c, #1f2347)',
        borderRadius: '14px',
        padding: '14px',
        width: '140px',
        height: '140px',
        border: '1px solid rgba(167, 139, 250, 0.08)',
        cursor: 'pointer',
        transition: 'all 0.25s ease',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '8px',
        boxSizing: 'border-box',
        '&:hover': {
            border: '1px solid rgba(167, 139, 250, 0.25)',
            transform: 'translateY(-2px)',
            boxShadow: '0 8px 20px rgba(0, 0, 0, 0.3)',
        },
    },
    cardEmoji: {
        fontSize: '2.4rem',
    },
    cardName: {
        fontSize: '0.82rem',
        fontWeight: 600,
        color: '#e2e8f0',
        textAlign: 'center',
    },
    cardMeta: {
        display: 'flex',
        gap: '6px',
        alignItems: 'center',
        flexWrap: 'wrap',
        justifyContent: 'center',
    },
    colorDot: {
        width: '10px',
        height: '10px',
        borderRadius: '50%',
        border: '1px solid rgba(255,255,255,0.15)',
    },
    cardType: {
        fontSize: '0.68rem',
        color: '#64748b',
        fontWeight: 500,
        textTransform: 'capitalize',
    },

    emptyState: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '48px 28px',
        color: '#475569',
        fontSize: '0.9rem',
        gap: '8px',
    },
    emptyIcon: {
        fontSize: '2.5rem',
        opacity: 0.5,
    },

    addButton: {
        background: 'linear-gradient(135deg, #7c3aed, #a78bfa)',
        border: 'none',
        borderRadius: '24px',
        color: '#fff',
        padding: '8px 22px',
        fontSize: '0.85rem',
        fontWeight: 600,
        cursor: 'pointer',
        transition: 'all 0.25s ease',
        boxShadow: '0 2px 8px rgba(124, 58, 237, 0.35)',
        '&:hover': {
            background: 'linear-gradient(135deg, #6d28d9, #8b5cf6)',
            boxShadow: '0 4px 14px rgba(124, 58, 237, 0.5)',
            transform: 'translateY(-1px)',
        },
    },

    addForm: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '14px',
        padding: '16px 28px 28px',
        borderTop: '1px solid rgba(167, 139, 250, 0.1)',
    },
    addFormRow: {
        display: 'flex',
        gap: '10px',
        flexWrap: 'wrap' as const,
    },
    addInput: {
        flex: 1,
        minWidth: '120px',
        background: 'rgba(255, 255, 255, 0.06)',
        border: '1.5px solid rgba(255, 255, 255, 0.1)',
        borderRadius: '12px',
        padding: '10px 14px',
        fontSize: '0.85rem',
        color: '#fff',
        outline: 'none',
        fontFamily: 'inherit',
        transition: 'all 0.25s ease',
        '&:focus': {
            borderColor: '#a78bfa',
            background: 'rgba(167, 139, 250, 0.08)',
        },
        '&::placeholder': {
            color: 'rgba(255, 255, 255, 0.2)',
        },
    },
    addSelect: {
        flex: 1,
        minWidth: '120px',
        background: 'rgba(255, 255, 255, 0.06)',
        border: '1.5px solid rgba(255, 255, 255, 0.1)',
        borderRadius: '12px',
        padding: '10px 14px',
        fontSize: '0.85rem',
        color: '#fff',
        outline: 'none',
        fontFamily: 'inherit',
        cursor: 'pointer',
        transition: 'all 0.25s ease',
        '&:focus': {
            borderColor: '#a78bfa',
            background: 'rgba(167, 139, 250, 0.08)',
        },
        '& option': {
            background: '#12162e',
            color: '#fff',
        },
    },
    submitButton: {
        background: 'linear-gradient(135deg, #7c3aed, #a78bfa)',
        border: 'none',
        borderRadius: '12px',
        color: '#fff',
        padding: '10px',
        fontSize: '0.85rem',
        fontWeight: 600,
        cursor: 'pointer',
        fontFamily: 'inherit',
        transition: 'all 0.25s ease',
        boxShadow: '0 2px 8px rgba(124, 58, 237, 0.35)',
        '&:hover': {
            background: 'linear-gradient(135deg, #6d28d9, #8b5cf6)',
        },
        '&:disabled': {
            opacity: 0.6,
            cursor: 'not-allowed',
        },
    },
    error: {
        background: 'rgba(239, 68, 68, 0.1)',
        border: '1px solid rgba(239, 68, 68, 0.3)',
        borderRadius: '10px',
        padding: '8px 12px',
        color: '#fca5a5',
        fontSize: '0.8rem',
        textAlign: 'center' as const,
    },
    loading: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '48px 28px',
        color: '#64748b',
        fontSize: '0.9rem',
    },
});

export default styles;
